### ISSUE TITLE
Replace man-db patch with configure options?

### ISSUE THREAD

**Issue by cjwatson** [ylluminarious/homebrew-man-db#1]
https://github.com/ylluminarious/homebrew-man-db/blob/13c998cb59f96c64208aea868425374587ed2d02/Formula/man-db.rb#L10-L14

Hi - I'm the upstream for libpipeline and man-db.  Have you considered configuring man-db with either `--enable-cache-owner=root` or `--disable-cache-owner --disable-setuid` (depending on whether you actually want man and mandb to be setuid so that they can write cached versions of manual pages - if you don't have a long tradition of users expecting the caching behaviour then you probably want to go with non-setuid)?  You could then drop your man-db patch.

I hadn't heard about the build issues on macOS before somebody brought them up on the groff mailing list recently.  If there were some way I could get temporary SSH access to a macOS system with enough bits installed for me to do test builds from git clones of gnulib, libpipeline, and man-db, I'd be happy to try to sort out upstreamable fixes.

**Comment by ylluminarious** [comment]
@cjwatson Thanks for the feedback! What you say is interesting--I was not aware of what exactly was causing the issue that necessitates this patch. So what I gather from what you're saying is that `man` and `man-db` actually use the `man:man` ownership on Linux for storing cached versions of man pages? And that by using your first configuration option you can set the owner to `root` instead? And by using your second set of options you disable the caching altogether?

If my understanding is correct, then this is actually pretty interesting. I did not know that `man-db` actually featured caching of man pages. That is quite a nice feature and would help me with `man-mode` in Emacs where man page rendering is sometimes slow. This would be be a slightly unorthodox practice for a Homebrew program, but I'm thinking of moving this program to MacPorts anyway, where `root` is embraced instead of shunned.

**Comment by cjwatson** [comment]
In limited circumstances, yes.  Saving cached rendered pages ("cat files") is only possible if the results are standard enough; for example, page rendering depends on terminal width (unless you set the `MANWIDTH` environment variables), and by default `man` will only save cat files if the terminal width is the historical norm of 80.  Realistically, cat files have to be owned by some system user if you're on any kind of multi-user system, so in order to make that work `man` has to be installed setuid to that system user.  Your understanding of the `./configure` options is correct.

It's interesting that you say that rendering is slow, since it's well over ten years since I heard anyone say that who was using anything resembling a modern system.  The very largest manual page I have here (`zshall(1)`) renders in under a second on my laptop, and more typical pages take more like 0.2 seconds.  Before making any major rearrangements, you should probably look into whether the problem is actually in `man-mode`, since if so then caching might not actually help very much.

I recommend against making `man` setuid root.  It's *possible*, yes, but it's a lot of unnecessary security exposure.  If you're going to enable cached pages, you should really have a dedicated user for the purpose and install `man` setuid to that (the `man` user and group aren't Linux-specific or anything, of course).  If it isn't possible for formulae to create their own users, then it would be best to use `--disable-cache-owner --disable-setuid`.

Before enabling caching in your packaging, you should also understand the locations where cat files and index databases will be written, and work out whether those are appropriate in the context of your packaging system.

If Homebrew and MacPorts have different practices (I'm unfamiliar with either), then I guess another possibility would be to just configure the two differently.  Of course how you spend your time is up to you, but in general I'm interested in making sure man-db is as widely available as possible.

**Comment by ylluminarious** [comment]
@cjwatson Thanks again for the feedback and thanks for clarifying whether my understanding was correct. So, I had a look at `man-mode` in Emacs and it turns out that it is definitely the bottleneck. It's not just running plain `man`, but is actually running a number of commands to help it format or clean things up. From `man.el`:

```elisp
;; ========== Features ==========
;; + Runs "man" in the background and pipes the results through a
;;   series of sed and awk scripts so that all retrieving and cleaning
;;   is done in the background.  The cleaning commands are configurable.
...
```

I ran `M-x man zshall` and found this to be the command that was invoked:

```sh
sh -c man -E ascii  zshall 2>/dev/null | sed  -e '/^[-][-]*$/d' -e '/[789]/s///g' -e '/Reformatting page.  Wait/d' -e '/Reformatting entry.  Wait/d' -e '/^[ 	]*Hewlett-Packard[ 	]Company[ 	]*-[ 	][0-9]*[ 	]-/d' -e '/^[ 	]*Hewlett-Packard[ 	]*-[ 	][0-9]*[ 	]-.*$/d' -e '/^[ 	][ 	]*-[ 	][0-9]*[ 	]-[ 	]*Formatted:.*[0-9]$/d' -e '/^[ 	]*Page[ 	][0-9]*.*(printed[ 	][0-9\/]*)$/d' -e '/^Printed[ 	][0-9].*[0-9]$/d' -e '/^[ 	]*X[ 	]Version[ 	]1[01].*Release[ 	][0-9]/d' -e '/^[A-Za-z].*Last[ 	]change:/d' -e '/^Sun[ 	]Release[ 	][0-9].*[0-9]$/d' -e '/[ 	]*Copyright [0-9]* UNIX System Laboratories, Inc.$/d' -e '/^[ 	]*Rev\..*Page [0-9][0-9]*$/d' | awk '
 BEGIN { blankline=0; anonblank=0; }
 /^$/ { if (anonblank==0) next; }
 { anonblank=1; }
 /^$/ { blankline++; next; }
 { if (blankline>0) { print ""; blankline=0; } print $0; }
 '
```

I haven't dissected all of that, but from a glance I can see plenty of opportunities for bottleneck which have little to do with `man` itself. So, as you say, now I'm not so sure whether caching would help this situation. Probably the best thing to do would be to configure and optimize these commands, as per the above comment. But I think I'll leave that for another day; I rarely use man pages as big as `zshall`.

Thanks for your other tips about `setuid`. Yes, formulae do not create their own users/groups because [Homebrew disallows usage of `sudo`.](https://docs.brew.sh/FAQ#why-does-homebrew-say-sudo-is-bad) There is [a workaround,](https://apple.stackexchange.com/questions/282567/how-do-i-run-homebrew-as-root) but it's a bit hacky and not guaranteed to work forever. So it seems caching is a no-go on Homebrew.

MacPorts, on the other hand, is just fine with `sudo` and actually requires it most of the time. It can create users/groups without a problem. I think `wireshark` requires its own user/group also, and MacPorts does this just fine. Conversely, I believe Homebrew has to work around this.

> Before enabling caching in your packaging, you should also understand the locations where cat files and index databases will be written, and work out whether those are appropriate in the context of your packaging system.

Yes, I think this would be little to no problem for either one.

> If Homebrew and MacPorts have different practices (I'm unfamiliar with either), then I guess another possibility would be to just configure the two differently. Of course how you spend your time is up to you, but in general I'm interested in making sure man-db is as widely available as possible.

I think I will end up configuring both packages in the same way. Caching sounds like it will have marginal impact and be a bit more trouble than its worth. However, I don't think I'll re-submit my formula to the Homebrew maintainers once I remove the patch because I have stopped using Homebrew as much as possible, switching to MacPorts instead. I've found it to be a superior package manager in a number of ways and I also had [a bit of a spat](https://github.com/Homebrew/homebrew-core/pull/25376) last time I submitted this package, [wherein I detailed my issues with Homebrew in general.](https://github.com/Homebrew/homebrew-core/pull/25376#issuecomment-376046845)

**Comment by cjwatson** [comment]
OK, so ideally you'd just pass the `--disable-...` options to configure without caching, then, and you could drop your `src/Makefile*` patch.  The set-id handling is complicated, security-critical, and best avoided if it isn't really needed.

I saw the previous spat; that's how I ended up here.  I was hoping that if I could help you get to the point of needing no patches, then it would bypass the problems that led to the spat in the first place. :-)

**Comment by ylluminarious** [comment]
@cjwatson Ok, so I followed your advice and removed the patch in the `man-db` formula, but I could not remove the patch for `libpipeline`. When I tried to do that, I got the following error in compilation:

```
==> Installing man-db from ylluminarious/man-db
==> Installing dependencies for ylluminarious/man-db/man-db: libpipeline
==> Installing ylluminarious/man-db/man-db dependency: libpipeline
==> Downloading https://download.savannah.nongnu.org/releases/libpipeline/libpipeline-1.5.0.tar.gz
==> Downloading from https://quantum-mirror.hu/mirrors/pub/gnusavannah/libpipeline/libpipeline-1.5.0.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/libpipeline/1.5.0 --disable-cache-owner --disable-setuid
==> make
Last 15 lines from /Users/my_username/Library/Logs/Homebrew/libpipeline/02.make:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libgnu.a(xsize.o) has no symbols
Making all in lib
  CC       libpipeline_la-appendstr.lo
  CC       libpipeline_la-pipeline.lo
  CC       libpipeline_la-debug.lo
  CCLD     libpipeline.la
Undefined symbols for architecture x86_64:
  "_program_name", referenced from:
      _error in libgnu.a(error.o)
      _error_at_line in libgnu.a(error.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libpipeline.la] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by cjwatson** [comment]
Thanks for the changes, although please note that you should only pass those two `./configure` options to man-db's `./configure` script, not libpipeline's.

I looked into the libpipeline problem.  I think this was fixed in https://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=commitdiff;h=f29814b96c9737abc8193d57d630697700feebeb (in combination with earlier work to add the `getprogname` module).  I've already updated libpipeline to a new enough version of Gnulib for this, but it was since 1.5.0 and I haven't yet made a release.  I'll sort that out.

**Comment by cjwatson** [comment]
OK, I've released libpipeline 1.5.1, which should stand a better chance of working without that patch.  Could you please give it a go?

**Comment by ylluminarious** [comment]
@cjwatson Ok, that did the trick. I was able to remove the patch for `libpipeline` as well. So now both formulas no longer have patches attached. I will try to submit this program to MacPorts now that we have this resolved.

Unfortunately, my previous conflict with the Homebrew maintainers makes me a little uncomfortable about submitting these formulas to them again. I apologize, I'm not trying to be difficult or stubborn. I honestly just don't want to cause any trouble in case there are any lingering hard feelings.

I am fine with anyone else submitting these formulas instead; they are licensed under the BSD-3 license which is in the root of the project directory. As long as the terms are followed, I see no problems with that.

I'll go ahead and close this ticket now, since we have solved the issue you originally brought up.

**Comment by cjwatson** [comment]
Great, thanks, and I understand.  I've asked on the groff list, and failing that will ask around elsewhere.

**Comment by ylluminarious** [comment]
@cjwatson Thanks, I appreciate it. Please let me know if something good turns up.

**Comment by Alhadis** [comment]
Hey guys, I've submitted this in Homebrew/homebrew-core#36469. Thanks so much for all your hard work. 👍

**Comment by ylluminarious** [comment]
@cjwatson @Alhadis Sorry for the drama that happened over on that PR. It's really a shame that their maintainers can be so overbearing.

[Here's a comment I made to the two of you that was deleted:](https://github.com/Homebrew/homebrew-core/pull/36469#issuecomment-458712346)
<br>
> @cjwatson @Alhadis I apologize for the difficulty you guys had here. It's too bad to see efforts like these go down the drain. I thought it might actually get in this time as per our other discussion. It's too bad this kind of conflict is rather prevalent in Homebrew. It stops lots of programs from getting in and other good things from happening. Some members of my team and I have moved to another package manager for macOS and we've been happier with it, both in terms of usage and in terms of interactions with its developers.

> No one need reply to this comment; I'm not trying to take any sides or get on anyone's nerves. I'm just offering an apology to the two who really tried to get this program in.

**Comment by Alhadis** [comment]
I appreciate it. Truth be known, I felt like the PR was doomed the moment they told me it needed to be keg-only. Homebrew used to be more programatic than this, now they're just spending more of their time finding ways to get worked up over people's "attitude".

I emailed @cjwatson with ths:

> Don't worry about the rejected PR, I'll start a tap (Homebrew's version of apt-get's "PPA", really)
> where I can add formulae for Heirloom Troff, Neatroff, historical Troffs, and shit, even packages to
> share tmacs people have written. =)
>
> So you'll be able to point people there with instructions on how to get man-db installed on a macOS > with Homebrew.

**Comment by Alhadis** [comment]
<img src="https://user-images.githubusercontent.com/2346707/51942130-6d46ca80-246a-11e9-8915-89c4ed2504b1.png" alt="Cunts" />

**Comment by Alhadis** [comment]
He banned me from ever contributing to Homebrew again, but that's alright, because I'm in a long-term migration away from anything macOS related.... hmmmm... Ubuntu's lookin' pretty good now. :D

**Comment by ylluminarious** [comment]
@Alhadis Wow, that's harsh. It's surprising that people who go on about respect so much can be so snappish. I've learned in my life that some of the people who go on about respect that much can be some of the most disrespectful.

WRT Ubuntu: I'm glad that's going for you 😄. Unfortunately, my situation isn't so convenient. I require macOS for certain things in my work, which just don't work or aren't up to snuff on Linux. It's a shame because Apple keeps making poor decisions [like their recent banning of Nvidia cards,](https://appleinsider.com/articles/19/01/18/apples-management-doesnt-want-nvidia-support-in-macos-and-thats-a-bad-sign-for-the-mac-pro) and to top that off, the main package manager for open-source stuff is filled with iron-fisted maintainers. Thus, I've had to switch to MacPorts which has actually been a better package manager overall. I'll try to get `man-db` in there and I don't anticipate any such problems as you guys have had with Homebrew.

**Comment by Alhadis** [comment]
Homebrew is just as bad as Stack Overflow — Invaluable, quality service you can't live without... moderated by the biggest pack of over-sensitive dickheads you'll come across.

Anyway, I have a special reason to be stuck using a MacBook for a while (it's not even mine though 😀). Basically, I'm working on a [huge project](https://github.com/Alhadis/Roff.js) that actually benefits from the crappy version of `groff` that most MacBooks have installed by default. Getting the library tested and running on Mac will cover much of the worst-possible scenarios the project will be used on.

**Comment by Alhadis** [comment]
The other reason I'm stuck on macOS is my dependency on Adobe products . 😢 They no work on Ubuntu/OpenBSD/etc

**Comment by ylluminarious** [comment]
> Homebrew is just as bad as Stack Overflow — Invaluable, quality service you can't live without... moderated by the biggest pack of over-sensitive dickheads you'll come across.

Lol, this is true. I guess "monopoly" is the name of the game. I'm hoping that MacPorts will make a comeback someday in the future, but it's just as unlikely as something that will replace StackOverflow.

Good luck with your project! Looks neat. If I had time to spare, I'd be interested in porting it to [Opal,](https://opalrb.com/) since I'm a Ruby fan myself :D

Yes, commercial stuff like Adobe really does only work well on macOS and Windows. I'd say that many such programs actually work better on macOS, from anecdotal experience. I'm also dependent on [Unity,](https://unity3d.com/) among other things.

Hopefully the state of computing will get better in the future, 'cause right now things are starting to look bleak...

**Comment by Alhadis** [comment]
The thing I'm gonna enjoy most about this tap is reformatting everything to use tabs, and fuck the shit out of Homebrew's picky coding style.

**Comment by ylluminarious** [comment]
Ha! Nice to see a fellow tabs man 😸 

We're becoming an endangered species in this day and age ;)

**Comment by Alhadis** [comment]
I don't normally follow many GitHub users, but shit, dude, that's what I keep saying whenever I discover another tabs user. 😢

**Comment by Alhadis** [comment]
[You might get a kick out of this](https://github.com/Alhadis/Coding-Style). :D I wrote it while high on energy drink, but the underlying content is still serious.

The source-code view of the `README.md` file will probably blow your mind, btw.

**Comment by cjwatson** [comment]
Well, that was all quite a trip.  Thanks to both of you for trying!  At least we got some useful code fixes out of the exercise.

> So you'll be able to point people there with instructions on how to get man-db installed on a macOS with Homebrew.

I've added some instructions along those lines to the [man-db homepage](https://nongnu.org/man-db/).

**Comment by Alhadis** [comment]
@cjwatson No need, I have something far more practical and better:
https://github.com/Alhadis/homebrew-troff

**Comment by Alhadis** [comment]
I'm going to make a formal announcement on the Groff mailing list calling for submissions for any *roff-related tools, ports, packages, etc, which I aim to make available via the Homebrew Tap.

I must apologise; I purposefully let that PR die after the maintainers told me they were serious about making a userland upgrade a "keg-only install". Honestly, this wasn't something I expected and it's extinguished any faith I have in the project's maintainers. This wasn't always the case... and had I known from the start they'd be forcing this to be keg-only, I would have spared everybody the trouble and just gone with the tap. 😞

**Comment by cjwatson** [comment]
> @cjwatson No need, I have something far more practical and better:
> https://github.com/Alhadis/homebrew-troff

I may be confused, but I thought that's what I linked to :-)

**Comment by Alhadis** [comment]
OH! Sorry, my brain's in three places at the moment. =) Thought you were referring to the last part of [this](https://github.com/Homebrew/homebrew-core/pull/36469#issuecomment-458628286):

>> but however it shakes out it would be nice to have a brief recipe that I can give to users to make man-db the default on their system if they want to do so.
>
> @cjwatson These are already automatically output for all keg_only software.

FYI, the first part of that post has me concerned:

> If we were adding it today `groff` probably would be as it's likely to interfere with builds the others are not. Newer formulae have a higher standard applied to them than existing formulae.

Going by Homebrew's history of turbulent policy changes, it's not unreasonable to expect they might end up making Groff keg-only, making it even harder for the macOS-using world to migrate away from Groff 1.19…

**Comment by Alhadis** [comment]
I mean, Homebrew have always kept certain formulae keg-only for very understandable reasons: things like `curl`, `openssl` and `llvm` are pretty pivotal to the continued operation of the system. But ruling out a replacement for `man`? Suggesting that `less`, `git` and `groff` should also be kept keg-only? Dooming users to a future of antique tools from ~2005 and earlier, because it's *safe* to keep them outdated?

I'm sorry, but that's completely fucked. Glad they've banned me from their repositories. :) I know now  not to praise Homebrew so kindly as I've done for so many years...
